### ISSUE TITLE
DB scripts (Forbedres / viderudvikles)

### ISSUE THREAD

**Issue by KasperOnFire** [KasperOnFire/FogEksamensProjekt#3]
Meter pris
Materiale pris

**Comment by CaptainVillain** [comment]
v1.0:

CREATE TABLE boards
(
bno int not null unique,
bwidth double not null,
ppmeter double not null,
primary key(bno)
);

CREATE TABLE roofing
(
ppmeter double not null,
primary key(ppmeter)
);

CREATE TABLE nailsscrews
(
pno int not null unique,
pname varchar(55),
price double not null,
primary key(pno)
);

CREATE TABLE orders
(
ono int not null unique,
length double not null,
width double not null,
price double not null,
rooftype varchar(55),
primary key(ono)
);

**Comment by DavidCarl** [comment]
Orders skal laves lidt om, vi skal havde foreign key som peger på et cno (customer number) og en int status som påpeger hvorvidt ordren er åben / lukket / ikke set

**Comment by DavidCarl** [comment]
CREATE TABLE IF NOT EXISTS orders
(
ono int not null unique,
cno int not null,
ostatus int not null,
length double not null,
width double not null,
price double not null,
rooftype varchar(55),
primary key(ono),
FOREIGN KEY(cno) REFERENCES user(UID)
);
